plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/ivicapanic/Desktop/Desktop – Ivica's MacBook Pro/Claude Code/generative-organism"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]